CC = gcc
CFlags = -Wall -pedantic -std=gnu99 -I/local/courses/csse2310/include \
	 -L/local/courses/csse2310/lib -lcsse2310a1 -g

uqwordiply: uqwordiply.c
	$(CC) $(CFlags) -o $@ $<


clean:
	rm uqwordiply

