CC=gcc
INCLUDEDIR=/local/courses/csse2310/include
LIBDIR=/local/courses/csse2310/lib
CFLAGS=-std=gnu99 -Wall -pedantic -g -I$(INCLUDEDIR)
LDFLAGS=-L$(LIBDIR) -lcsse2310a3

PROG=testuqwordiply

$(PROG): $(PROG).o

clean:
	rm -f *.o $(PROG)
